name = "CrossMappings"
uuid = "7011085d-2e9b-5a7b-b0c2-f102c05e50c2"
authors = ["Kristian Agasøster Haaga <kahaaga@gmail.com>", "Tor Einar Møller <temolle@gmail.com>"]
version = "0.4.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StateSpaceReconstruction = "1441a9f6-6a74-5418-a591-cdf1d78a07f0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UncertainData = "dcd9ba68-c27b-5cea-ae21-829cd07325bf"

[compat]
Conda = "^1.3"
DelayEmbeddings = "^1.3"
Distances = "^0.8.2, ^1"
Distributions = "^0.22.3, ^1"
NearestNeighbors = "^0.4.4, ^1"
PyCall = "^1.91.2, ^1"
Requires = "^0.5.2, ^1"
StateSpaceReconstruction = "^0.4.2, ^1"
StatsBase = "^0.32, ^1"
UncertainData = "^0.6, ^1"
julia = "^1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
